config/routes.rb
Rails.application.routes.draw do

  get "sign_up" , to: "registrations#new"
  post "sign_up" , to: "registrations#create"

  get "sign_in" , to: "sessions#new" 
  post "sign_in" , to: "sessions#create"

  get "/dashboard/password" , to: "passwords#edit" ,as: :edit_password
  patch "/dashboard/password" , to: "passwords#update"

  get "/dashboard", to: "dashboards#new", as: "dashboard"

  get "/dashboard/rental_stations", to: "dashboards#rental_stations", as: "dashboard_rental_stations"

  get "/dashboard/rental_stations/new", to: "rental_stations#new", as: "new_rental_station"
  post "/dashboard/rental_stations", to: "rental_stations#create"



  get "/rental_stations", to: "rental_stations#all", as: "rental_stations"
  get "/rental_stations/:id", to: "rental_stations#show", as: "rental_station"

  delete "/rental_stations/:id", to: "rental_stations#destroy", as: "delete_rental_station"

  get "/rental_stations/:id/edit", to: "rental_stations#edit" , as: "edit_rental_station"
  patch "/rental_stations/:id" , to: "rental_stations#update"


  get "/rental_stations/:id/vehicles" ,  to:"vehicles#index", as: "rental_station_vehicles"

  get "/rental_stations/:id/vehicles/new", to: "vehicles#new", as: "new_rental_station_vehicle"
  post "/rental_stations/:id/vehicles", to: "vehicles#create" 


  get "/rental_stations/:id/vehicles/:vehicle_id/edit", to: "vehicles#edit", as: "edit_rental_station_vehicle"
  patch "/rental_stations/:id/vehicles/:vehicle_id", to: "vehicles#update" , as: "rental_station_vehicle"

  delete "/rental_stations/:id/vehicles/:vehicle_id", to: "vehicles#destroy", as: "delete_rental_station_vehicle"

  delete "logout" , to:"sessions#destroy"

  get "/dashboard/my_vehicles", to: "dashboards#my_vehicles", as: "dashboard_my_vehicles"

  post "/vehicles/:vehicle_id/bookings", to: "bookings#create", as: "create_vehicle_booking"

  post "/bookings/:id/accept", to: "bookings#accept", as: "accept_booking"
  post "/bookings/:id/complete", to: "bookings#complete", as: "complete_booking"
  post "/bookings/:id/cancel", to: "bookings#cancel", as: "cancel_booking"

  get "/dashboard/all_bookings", to: "dashboards#all_bookings", as: "all_bookings"

  get "/dashboard/rental_history" , to: "rental_history#show", as: "rental_history" 

  get "/dashboard/all_bookings/:id/review", to: "dashboards#review", as: "review_booking"
  post "/dashboard/bookings/:id/review", to: "dashboards#create_review", as: "create_review"

  get "rental_stations/:id/vehicles/review" , to: "vehicles#review", as: "vehicle_reviews"
  get "/rental_stations/:id/review" , to: "rental_stations#review", as: "station_reviews"

  get '/language/:locale', to: 'language#switch', as: 'language_switch'

  

  root to:"main#index"
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible fade show mt-2" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger alert-dismissible fade show mt-2" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark border-bottom border-body" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/"><%= t('app_name') %></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <li class="nav-item">
                    <%= link_to t('nav.rental_stations'), rental_stations_path , class: "nav-link" %>
                </li>
                <% if Current.user %>

                <li class="nav-item">

                    <%= button_to t('nav.logout'), logout_path,method: :delete , class: "nav-link" %>
                </li>

                <li class="nav-item">
                    <div class="d-flex">

                        <%= link_to t('nav.dashboard'), dashboard_path, class: "nav-link" %>
                        <% if Current.user && Booking.where(provider_id: Current.user.id, status: "pending").any? %>
                        <i class="fa-solid fa-circle fa-2xs" style="color: #FF0000;margin-top:0.55rem;margin-left:-0.2rem;"></i>

                        <% elsif Current.user && Booking.where(customer_id: Current.user.id, status: "pending").any? %>
                        <i class="fa-solid fa-circle fa-2xs" style="color: #FF0000;margin-top:0.55rem;margin-left:-0.5rem;"></i>

                        <% elsif Current.user && Booking.where(customer_id: Current.user.id, status: "accepted").any? %>
                        <i class="fa-solid fa-circle fa-2xs" style="color: #FF0000;margin-top:0.55rem;margin-left:-0.5rem;"></i>


                        <% end %>
                    </div>
                </li>

                <% else %>
                <li class="nav-item">
                    <%= link_to t('nav.signup'), sign_up_path ,class: "nav-link" %>
                </li>
                <li class="nav-item">

                    <%= link_to t('nav.login'), sign_in_path, class: "nav-link" %>

                </li>

                <% end %>
                <li class="nav-item dropdown mt-1">
                    <a class="nav-link dropdown-toggle py-1" href="#" id="languageDropdown" role="button" 
                       data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="bi bi-globe fs-6"></i>
                    <span class="d-none d-lg-inline-block ms-1 small"><%= t('nav.language') %></span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="languageDropdown">
                        <li>
                            <%= link_to language_switch_path(locale: :en), class: "dropdown-item #{I18n.locale == :en ? 'active' : ''}" do %>
                            <span class="flag-icon flag-icon-us me-2 small"></span> English
                            <% end %>
                        </li>
                        <li>
                            <%= link_to language_switch_path(locale: :hi), class: "dropdown-item #{I18n.locale == :hi ? 'active' : ''}" do %>
                            <span class="flag-icon flag-icon-in me-2 small"></span> हिन्दी
                            <% end %>
                        </li>
                    </ul>
                </li>







            </ul>
        </div>
    </div>
</nav>